### ISSUE TITLE
Excellent.  Maybe we can document here or on wiki.

### ISSUE THREAD

**Issue by clort81** [maemo-leste-extras/desktop-cmd-exec#1]
Maybe we can document here some useful commands to add to desktop-launched commands.

**Comment by MerlijnWajer** [comment]
I've been adding wiki pages for some of the extras packages, so if you make one for desktop-cmd-exec, that would be a good place: https://leste.maemo.org/Category:Extras

**Comment by sicelo** [comment]
I think we should close this issue, as any commands that we may come up with will not really be specific to DCEW.
While working on maemo-leste/bugtracker#558 , I took the opportunity to remove the obsolete commands from Fremantle, and adjust those that still work.

Any objections?

**Comment by clort81** [comment]
not from me.  this is just great. i'm gonna have widgets to peek at webcam, to do blinkenlights scripts, turn on usb networking, set charging current, set backlight level yay
